### ISSUE TITLE
Not destroying bugs is a bug in itself - the player does not lose a life

### ISSUE THREAD

**Issue by blastoise186** [T-J-D-Cavey/Click-a-Bug#5]
It appears that not destroying bugs carries no penalty for the player, except for not gaining points. This isn't usually how these games work and doesn't appear to be intended.

Steps to reproduce:

1. Start the game
2. Destroy a few bugs
3. Let LOADS of bugs go through untouched
4. Watch the life counter not deplete

**Comment by T-J-D-Cavey** [comment]
This is intended behavior. Not clicking a bug does not produce a penalty. 

At the later stages of the game, the bugs appear and disappear so quickly that a penalty for not clicking would be too hard. Instead, a short timer provides the incentive to click a bug as fast as possible. 

Possible hard mode could include missed bug click penalties
